export const SET_USER = "SET_USER"
export const CLEAR_USER = "CLEAR_USER"
export const SET_TEMP_USER = "SET_TEMP_USER"
export const CLEAR_TEMP_USER = "CLEAR_TEMP_USER"
export const SET_PAGE = "SET_PAGE"
